#!bin/bash

git clone https://"$GITHUB_USER":"$GITHUB_PASS"@github.com/"$GITHUB_USER"/"$GH_PVT_REPO_NAME"

mv /home/$GH_PVT_REPO_NAME/session/* /home/

echo Loading the config:\n
echo | tee /home/.config/rclone/rclone.conf << EOF
[GC]
type = drive
scope = drive
service_account_file = /home/$GH_PVT_REPO_NAME/sa/*.json
service_account_file_path = /home/$GH_PVT_REPO_NAME/sa
EOF

ls -R

python3 /home/scriptdir/tg_channel_downloader.py
