#!bin/bash

git clone https://"$GITHUB_USER":"$GITHUB_PASS"@github.com/"$GITHUB_USER"/"$GH_PVT_REPO_NAME"

cp /home/$GH_PVT_REPO_NAME/session/* /home/

echo Loading the config:
echo | tee /home/.config/rclone/rclone.conf << EOF
[GC]
type = drive
scope = drive
service_account_file = /home/$GH_PVT_REPO_NAME/sa/*.json
service_account_file_path = /home/$GH_PVT_REPO_NAME/sa
EOF

sed -i \
    -e 's/\(api_id=\).*/\1'$API_ID'/' \
    -e 's/\(api_hash=\).*/\1'$API_HASH'/' \
    -e 's/\(bot_token=\).*/\1'$BOT_TOKEN'/' \
    -e 's/\(admin_id=\).*/\1'$ADMIN_ID'/' \
    -e 's/\(drive_id=\).*/\1'$DRIVE_ID'/' \
    /home/tg_channel_downloader.py

python3 /home/tg_channel_downloader.py
